---
title: "Results: Random atlases"
author: "Anna Elisabeth Furtjes"
highlighter: prettify
output: 
  html_document:
    code_folding: hide
    theme: spacelab
    includes:
      after_body: footer.html
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, eval = FALSE)
knitr::opts_knit$set(root.dir = "C:/Users/k1894405/OneDrive - King's College London/PhD/Projects/Comparing labelling protocols/results/nulldistr")

```

```{r eval=T}
# create data.frame to store results
results = data.frame(matrix(nrow = 7*3*3, ncol = 8))
names(results) = c("num_ROIs", "meas","pheno","min","max","median","mean","sd")


# get all possible combinations of atlas, meas & pheno
num_ROIs = as.character(c(34, 68, 148, 274, 334, 360, 500))
meas = c("SurfArea","GrayVol","ThickAvg")
pheno = c("age","gpheno","sex")
results[,c("num_ROIs","meas","pheno")] = expand.grid(num_ROIs, meas, pheno)


for(i in num_ROIs){
  #i = 500
  null = read.table(paste0("morph_results_",i,"randomROIs.table"), header=T)
  
  # change measurement type names from randomaparc
  null$meas[which(null$meas == "area")] = "SurfArea"
  null$meas[which(null$meas == "volume")] = "GrayVol"
  null$meas[which(null$meas == "thickness")] = "ThickAvg"

  for(j in c("SurfArea","GrayVol","ThickAvg")){
    
    for(k in c("age","gpheno","sex")){
      # subset data.frame
      subset = null[which(null$meas == j & null$pheno == k),]
    
      
      #### store results
      # mean morph
      results$mean[which(results$num_ROIs == i & results$meas == j & results$pheno == k)] = mean(subset$morph, na.rm=T)
      # sd morph
      results$sd[which(results$num_ROIs == i & results$meas == j & results$pheno == k)] = sd(subset$morph, na.rm=T)
      # min morph
      results$min[which(results$num_ROIs == i & results$meas == j & results$pheno == k)] = min(subset$morph, na.rm=T)
      # max morph
      results$max[which(results$num_ROIs == i & results$meas == j & results$pheno == k)] = max(subset$morph, na.rm=T)
      # median morph
      results$median[which(results$num_ROIs == i & results$meas == j & results$pheno == k)] = median(subset$morph, na.rm=T)
      
    }
    
  }
  

}

# round values
results[,c("min","max","median","mean","sd")]=round(results[,c("min","max","median","mean","sd")], digits=2)

# order frame
results=results[order(results$num_ROIs),]

library(DT)
datatable(results, rownames=FALSE, filter="top",options= list(pageLength=10,scrollX=T), caption = "Descriptive statistics morphometricity estimates random atlases")
```



This table is stored in an excel sheet using the code below
```{r}
# store in Excel sheet
```

